R-Matrices

In [1]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix
thismatrix[1, 2]

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

[1] "cherry"

In [2]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig", "water"), nrow = 5, ncol = 2)
thismatrix


[,1]   [,2]     
[1,] apple  pineapple
[2,] banana pear     
[3,] cherry melon    
[4,] orange fig      
[5,] grape  water

In [3]:
thismatrix[c(1,2,5),]

[,1]   [,2]     
[1,] apple  pineapple
[2,] banana pear     
[3,] grape  water

In [4]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

"apple" %in% thismatrix

[1] TRUE

In [5]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

[,1]       [,2]      [,3]     
[1,] apple      orange    pear     
[2,] banana     grape     melon    
[3,] cherry     pineapple fig      
[4,] strawberry blueberry raspberry

In [6]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"


In [7]:
# Combine matrices
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Adding it as a rows
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

# Adding it as a columns
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined

[,1]   [,2]      
[1,] apple  cherry    
[2,] banana grape     
[3,] orange pineapple 
[4,] mango  watermelon

[,1]   [,2]   [,3]   [,4]      
[1,] apple  cherry orange pineapple 
[2,] banana grape  mango  watermelon

In [1]:
# Create a data frame
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Print the data frame
Data_Frame

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

In [2]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame

summary(Data_Frame)

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

     Training     Pulse          Duration   
 Other   :1   Min.   :100.0   Min.   :30.0  
 Stamina :1   1st Qu.:110.0   1st Qu.:37.5  
 Strength:1   Median :120.0   Median :45.0  
              Mean   :123.3   Mean   :45.0  
              3rd Qu.:135.0   3rd Qu.:52.5  
              Max.   :150.0   Max.   :60.0  

In [3]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame[1]

Data_Frame[["Training"]]

Data_Frame$Training

Training
1 Strength
2 Stamina 
3 Other

[1] Strength Stamina  Other   
Levels: Other Stamina Strength

[1] Strength Stamina  Other   
Levels: Other Stamina Strength

Add Rows

Use the rbind() function to add new rows in a Data Frame:

In [4]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Add a new row
New_row_DF <- rbind(Data_Frame, c("Strength", 110, 110))

# Print the new row
New_row_DF

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45      
4 Strength 110   110

In [5]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Remove the first row and column
Data_Frame_New <- Data_Frame[-c(1), -c(1)]

# Print the new data frame
Data_Frame_New

Pulse Duration
2 150   30      
3 120   45

In [6]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

dim(Data_Frame)

[1] 3 3

In [7]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

length(Data_Frame)

[1] 3

In [8]:
Data_Frame3 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame4 <- data.frame (
  Steps = c(3000, 6000, 2000),
  Calories = c(300, 400, 300)
)

New_Data_Frame1 <- cbind(Data_Frame3, Data_Frame4)
New_Data_Frame1

Training Pulse Duration Steps Calories
1 Strength 100   60       3000  300     
2 Stamina  150   30       6000  400     
3 Other    120   45       2000  300