In [10]:
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6,7,8,9), nrow = 3, ncol = 3)

# Print the matrix
thismatrix

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

R-Matrices

In [1]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix
thismatrix[1, 2]

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

[1] "cherry"

In [2]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", 
                       "pear", "melon", "fig", "water"), nrow = 5, ncol = 2)
thismatrix


[,1]   [,2]     
[1,] apple  pineapple
[2,] banana pear     
[3,] cherry melon    
[4,] orange fig      
[5,] grape  water

In [22]:
thismatrix[c(1,2,5),]

[,1]   [,2]     
[1,] apple  pineapple
[2,] banana pear     
[3,] grape  water

In [23]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

"grape" %in% thismatrix

[1] FALSE

In [15]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix



[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

In [16]:
thismatrix <- thismatrix[-c(1), -c(1) ]
thismatrix

[,1]      [,2] 
[1,] grape     melon
[2,] pineapple fig

use rbind() to add additional rows

In [4]:
newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

[,1]       [,2]      [,3]     
[1,] apple      orange    pear     
[2,] banana     grape     melon    
[3,] cherry     pineapple fig      
[4,] strawberry blueberry raspberry

use cbind() to add additional columns

In [5]:
newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))

# Print the new matrix
newmatrix

[,1]   [,2]      [,3]  [,4]      
[1,] apple  orange    pear  strawberry
[2,] banana grape     melon blueberry 
[3,] cherry pineapple fig   raspberry

In [17]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "strawberry", "blueberry"), nrow = 3, ncol = 2)
thismatrix

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

print("-----------------------")

for (columns in 1:ncol(thismatrix)) {
    for (rows in 1:nrow(thismatrix)) {
        print(thismatrix[rows, columns])
    }
}

[,1]   [,2]      
[1,] apple  orange    
[2,] banana strawberry
[3,] cherry blueberry

[1] "apple"
[1] "orange"
[1] "banana"
[1] "strawberry"
[1] "cherry"
[1] "blueberry"
[1] "-----------------------"
[1] "apple"
[1] "banana"
[1] "cherry"
[1] "orange"
[1] "strawberry"
[1] "blueberry"


In [18]:
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix1

[,1]   [,2]  
[1,] apple  cherry
[2,] banana grape

In [20]:
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)
Matrix2

[,1]   [,2]      
[1,] orange pineapple 
[2,] mango  watermelon

In [21]:
# Combine matrices
# Adding it as a rows
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

[,1]   [,2]      
[1,] apple  cherry    
[2,] banana grape     
[3,] orange pineapple 
[4,] mango  watermelon

In [22]:
# Adding it as a columns
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined

[,1]   [,2]   [,3]   [,4]      
[1,] apple  cherry orange pineapple 
[2,] banana grape  mango  watermelon

In [23]:
# Create a data frame
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Print the data frame
Data_Frame

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

In [2]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame

summary(Data_Frame)

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

     Training     Pulse          Duration   
 Other   :1   Min.   :100.0   Min.   :30.0  
 Stamina :1   1st Qu.:110.0   1st Qu.:37.5  
 Strength:1   Median :120.0   Median :45.0  
              Mean   :123.3   Mean   :45.0  
              3rd Qu.:135.0   3rd Qu.:52.5  
              Max.   :150.0   Max.   :60.0  

In [24]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame[2]

Data_Frame[["Training"]]

Data_Frame$Duration

Pulse
1 100  
2 150  
3 120

[1] Strength Stamina  Other   
Levels: Other Stamina Strength

[1] 60 30 45

Add Rows

Use the rbind() function to add new rows in a Data Frame:

In [37]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 40)
)
Data_Frame  
# Add a new row
New_row_DF <- rbind(Data_Frame, c("Strength", 110, 110))

# Print the new row
New_row_DF

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   40

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   40      
4 Strength 110   110

In [25]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 40)
)
Data_Frame  
# Add a new row
New_row_DF <- cbind(Data_Frame, Steps = c(1000, 6000, 2000))

# Print the new row
New_row_DF

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   40

Training Pulse Duration Steps
1 Strength 100   60       1000 
2 Stamina  150   30       6000 
3 Other    120   40       2000

In [40]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)
Data_Frame
# Remove the first row and column
#Data_Frame_New <- Data_Frame[-c(1), ]
Data_Frame_New <- Data_Frame[-c(1), -c(1)]

# Print the new data frame
Data_Frame_New

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

Pulse Duration
2 150   30      
3 120   45

In [41]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

dim(Data_Frame)

[1] 3 3

In [42]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

length(Data_Frame)

[1] 3

In [43]:
Data_Frame3 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)
Data_Frame3
Data_Frame4 <- data.frame (
  Steps = c(3000, 6000, 2000),
  Calories = c(300, 400, 300)
)
Data_Frame4

New_Data_Frame1 <- cbind(Data_Frame3, Data_Frame4)
New_Data_Frame1

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

Steps Calories
1 3000  300     
2 6000  400     
3 2000  300

Training Pulse Duration Steps Calories
1 Strength 100   60       3000  300     
2 Stamina  150   30       6000  400     
3 Other    120   45       2000  300

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

Steps Calories
1 3000  300     
2 6000  400     
3 2000  300

ERROR: Error in rbind(deparse.level, ...): numbers of columns of arguments do not match
